<script setup lang="ts">
    import { computed, ref } from 'vue'
    import { useRouter } from 'vue-router'
    import { ElMessage } from 'element-plus'
    import { CheckCircle2, Clock, MapPin, QrCode, UploadCloud } from 'lucide-vue-next'
    import { useEvaluationStore } from '@/stores/evaluation'
    import { useMarketStore } from '@/stores/market'
    import { matchScheduleEntry, parseIcs, parseXlsx, type RawScheduleEntry } from '@/utils/scheduleImport'

    const router = useRouter()
    const evaluationStore = useEvaluationStore()
    const marketStore = useMarketStore()
    const importDialogVisible = ref(false)
    const parsedEntries = ref<RawScheduleEntry[]>([])
    const parseError = ref('')

    const previewMatched = computed(() =>
      parsedEntries.value.map((entry) => ({ entry, stock: matchScheduleEntry(entry, marketStore.stocks) }))
      )
      const matchedCount = computed(() => previewMatched.value.filter((item) => item.stock).length)
      const unmatchedCount = computed(() => parsedEntries.value.length - matchedCount.value)

      function handleSignIn(sessionId: string) {
        const result = evaluationStore.signInCourse(sessionId)
          result.success ? ElMessage.success(result.message) : ElMessage.warning(result.message)
          }

          function goToEvaluation(sessionId: string) {
            router.push({ path: '/evaluation', query: { session: sessionId } })
            }

            async function handleFileChange(file: { raw?: File }) {
              parseError.value = ''
                parsedEntries.value = []
                  const raw = file.raw
                    if (!raw) return

                      try {
                          const name = raw.name.toLowerCase()
                              if (name.endsWith('.ics')) parsedEntries.value = parseIcs(await raw.text())
                                  else if (name.endsWith('.xlsx') || name.endsWith('.xls')) parsedEntries.value = parseXlsx(await raw.arrayBuffer())
                                      else {
                                            parseError.value = '仅支持 .xlsx / .xls / .ics 格式的课表文件'
                                                  return
                                                      }
                                                          if (parsedEntries.value.length === 0) parseError.value = '未从文件中解析到课程，请检查文件内容或表头格式'
                                                            } catch (error) {
                                                                parseError.value = '文件解析失败，请确认文件格式正确'
                                                                    console.error(error)
                                                                      }
                                                                      }

                                                                      function confirmImport() {
                                                                        const result = evaluationStore.importCourses(parsedEntries.value)
                                                                          if (result.imported > 0) {
                                                                              ElMessage.success(`成功导入 ${result.imported} 门课程${result.skipped > 0 ? `，跳过已存在 ${result.skipped} 门` : ''}`)
                                                                                } else if (result.skipped > 0) {
                                                                                    ElMessage.info('导入的课程均已存在于课表中')
                                                                                      }
                                                                                        if (result.unmatched.length > 0) ElMessage.warning(`${result.unmatched.length} 门课程未匹配到教师：${result.unmatched.join('、')}`)
                                                                                          importDialogVisible.value = false
                                                                                            parsedEntries.value = []
                                                                                            }
                                                                                            </script>

                                                                                            <template>
                                                                                              <div class="courses-view">
                                                                                                  <section class="courses-panel">
                                                                                                        <header class="courses-header">
                                                                                                                <div>
                                                                                                                          <p class="eyebrow">课程管理</p>
                                                                                                                                    <h2>我的课程</h2>
                                                                                                                                              <p>完成签到后即可前往评价中心为对应老师打分。</p>
                                                                                                                                                      </div>
                                                                                                                                                              <el-button type="primary" @click="importDialogVisible = true">
                                                                                                                                                                        <UploadCloud :size="16" /> 导入课表
                                                                                                                                                                                </el-button>
                                                                                                                                                                                      </header>

                                                                                                                                                                                            <div class="course-list">
                                                                                                                                                                                                    <article v-for="session in evaluationStore.courses" :key="session.id" class="course-item">
                                                                                                                                                                                                              <div class="course-main">
                                                                                                                                                                                                                          <h3>{{ session.courseName }}</h3>
                                                                                                                                                                                                                                      <p>{{ session.teacherName }}</p>
                                                                                                                                                                                                                                                  <div class="course-meta">
                                                                                                                                                                                                                                                                <span><Clock :size="13" /> {{ session.time }}</span>
                                                                                                                                                                                                                                                                              <span><MapPin :size="13" /> {{ session.room }}</span>
                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                              <div class="course-actions">
                                                                                                                                                                                                                                                                                                                          <el-button v-if="!session.isSigned" type="success" @click="handleSignIn(session.id)">
                                                                                                                                                                                                                                                                                                                                        <QrCode :size="15" /> 签到
                                                                                                                                                                                                                                                                                                                                                    </el-button>
                                                                                                                                                                                                                                                                                                                                                                <el-button v-else-if="!session.isEvaluated" type="primary" @click="goToEvaluation(session.id)">
                                                                                                                                                                                                                                                                                                                                                                              去评价
                                                                                                                                                                                                                                                                                                                                                                                          </el-button>
                                                                                                                                                                                                                                                                                                                                                                                                      <span v-else class="done"><CheckCircle2 :size="16" /> 已评</span>
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                        </article>
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                      <el-dialog v-model="importDialogVisible" title="导入课表" width="540px">
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="import-body">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <el-upload drag :auto-upload="false" :show-file-list="false" :on-change="handleFileChange" accept=".xlsx,.xls,.ics">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="upload-inner">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <UploadCloud :size="36" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>将课表文件拖到此处，或点击选择文件</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <small>支持 .xlsx / .xls / .ics，自动解析课程名称、教师、时间、地点</small>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </el-upload>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div v-if="parseError" class="parse-error">{{ parseError }}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div v-if="parsedEntries.length" class="parse-preview">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>解析到 {{ parsedEntries.length }} 条课程，可匹配 {{ matchedCount }} 条<span v-if="unmatchedCount">，未匹配 {{ unmatchedCount }} 条</span></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div v-for="(item, index) in previewMatched" :key="index" class="preview-row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span>{{ item.entry.courseName || '—' }}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span>{{ item.stock ? `${item.stock.name} · ${item.stock.department}` : '未匹配到教师' }}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <template #footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <el-button @click="importDialogVisible = false">取消</el-button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <el-button type="primary" :disabled="matchedCount === 0" @click="confirmImport">确认导入 ({{ matchedCount }})</el-button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </template>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </el-dialog>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </template>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <style scoped>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .courses-view { max-width: 980px; margin: 0 auto; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .courses-panel { padding: 26px; border: 1px solid rgba(148, 163, 184, .18); border-radius: 20px; background: rgba(17, 26, 44, .95); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .courses-header { display: flex; justify-content: space-between; align-items: flex-start; gap: 16px; padding-bottom: 20px; border-bottom: 1px solid rgba(148, 163, 184, .12); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .eyebrow { margin: 0 0 5px; color: #38bdf8; font-size: .76rem; font-weight: 700; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .courses-header h2 { margin: 0; color: #f8fafc; font-size: 1.45rem; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .courses-header p:not(.eyebrow) { margin: 7px 0 0; color: #94a3b8; font-size: .86rem; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .course-list { display: flex; flex-direction: column; gap: 10px; margin-top: 18px; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .course-item { display: flex; justify-content: space-between; gap: 16px; padding: 16px; border: 1px solid rgba(148, 163, 184, .12); border-radius: 14px; background: rgba(15, 23, 42, .55); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .course-main h3 { margin: 0; color: #f8fafc; font-size: .98rem; }.course-main p { margin: 5px 0; color: #cbd5e1; font-size: .84rem; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .course-meta { display: flex; flex-wrap: wrap; gap: 12px; color: #64748b; font-size: .76rem; }.course-meta span, .done { display: inline-flex; align-items: center; gap: 4px; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .course-actions { display: flex; align-items: center; flex-shrink: 0; }.done { color: #34d399; font-size: .86rem; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .import-body, .parse-preview { display: flex; flex-direction: column; gap: 12px; }.upload-inner { color: #38bdf8; }.upload-inner p { color: #e2e8f0; margin: 8px 0; }.upload-inner small { color: #94a3b8; }.parse-error { color: #f87171; }.parse-preview p { margin: 0; color: #94a3b8; font-size: .83rem; }.preview-row { display: flex; justify-content: space-between; gap: 12px; padding: 8px 10px; border-radius: 8px; background: rgba(15, 23, 42, .55); color: #cbd5e1; font-size: .8rem; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          @media (max-width: 640px) { .courses-panel { padding: 18px; }.courses-header, .course-item { flex-direction: column; }.course-actions { justify-content: flex-start; } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </style>

